services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres-server-open-webui
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - open-webui-dev

  # Servicio de Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OLLAMA_API: ${OLLAMA_API}
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - open-webui-dev

volumes:
  postgres-data:
  open-webui-data:

networks:
  open-webui-dev:
    name: open-webui-dev
    driver: bridge
